
wasd_mode = true

[normal]
return = "enter"
e = "eat_item"
i = "drop_item"
g = "pick_up_item"
h = "open_help_win"
o = "open_game_info_win"
q = "drink_item"
r = "release_item"
escape = "open_exit_win"
f1 = "open_item_menu"
f2 = "open_equip_win"
f3 = "open_status_win"
f4 = "open_creation_win"
f5 = "open_game_info_win"
f6 = "open_exit_win"
f12 = "open_debug_command_win"


[dialog]
return = "enter"
escape = "cancel"
tab = "rotate_window_right"
a = "item_infomation"
