
cursor_move_duration = 160 # in milli secs
gap_len_between_dialogs = 8

[color]
border_dark = { r=131, g=85, b=53 }
border_highlight_dark = { r=210, g=160, b=12 }
border_highlight_light = { r=250, g=220, b=12 }
border_light = { r=209, g=136, b=84 }
button_normal_bg = { r=4, g=10, b=20 }
button_normal_bg_covered = { r=39, g=40, b=42 }
button_normal_border_dark = { r=131, g=85, b=53 }
button_normal_border_light = { r=210, g=160, b=12 }
gauge_bg = { r=7, g=7, b =7 }
gauge_border_dark = { r=153, g=116, b =20 }
gauge_border_light = { r=229, g=211, b =4 }
gauge_exp = { r=153, g=153, b=117 }
gauge_hp = { r=237, g=47, b =37 }
gauge_sp = { r=200, g=200, b =0 }
gauge_work = { r = 224, g = 224, b = 20 }
list_border = { r=59, g=69, b=103 }
log_font = { r=250, g=250, b=250 }
log_window_bg = { r=20, g=4, b=4 }
normal_font = { r=250, g=250, b=250 }
sidebar_bg = { r=20, g=4, b=4 }
vscroll_border = { r=140, g=76, b=0 }
vscroll_border_inner = { r=94, g=51, b=0 }
vscroll_knob = { r=39, g=40, b=42 }
vscroll_knob_border = { r=218, g=129, b=22 }
window_bg = { r=4, g=10, b=20 }
window_bg_highlight = { r=34, g=40, b=60 }

[font]
s = { size=11 }
m = { size=16 }
log = { size=14 }

[log_window]
h = 19
n_display_line = 9

[exit_window]
rect = { x = -999, y = 120, w = 200, h = 100 }
list_y = 52

[help_window]
rect = { x = -999, y = -999, w = 450, h = 300 }
key_label_start = { x = 4, y = 4 }
key_label_h = 22

[talk_window]
rect = { x = -999, y = 50, w = 450, h = 200 }
text_wrap_width = 435
image_window_pos_x = -55
image_window_pos_y = 0

[msg_dialog]
rect = { x = -999, y = 120, w = 200, h = 0 }

[start_dialog]
rect = { x = -1000, y = -1000, w = 200, h = 72 }

[text_input_dialog]
rect = { x = -999, y = -999, w = 200, h = 40 }

[newgame_dialog]
explanation_text_rect = { x = -999, y = 50, w = 300 }

[choose_save_file_dialog]
rect = { x = -999, y = -1000, w = 300, h = 130 }
list_size = 5

[choose_class_dialog]
rect = { x = -999, y = -999, w = 200, h = 200 }

[creation_window]
rect = { x = -999, y = -999, w = 450, h = 300 }
n_row = 6
column_pos = [1, 50]

[creation_detail_dialog]
rect = { x = -999, y = -999, w = 450, h = 300 }
n_row = 7
column_pos = [1, 50, 400]
list_margin = 26
product_name = { x = 2, y = 2 }
facility_ok_icon_rect = { x = 2, y = 216, w = 24, h = 24 }
facility_label_rect = { x = 30, y = 216 }
enough_ingredients_icon_rect = { x = 2, y = 240, w = 24, h = 24 }
enough_ingredients_label_rect = { x = 30, y = 240 }
start_button_rect = { x = 60, y = 265, w = 100, h = 30 }
cancel_button_rect = { x = 290, y = 265, w = 100, h = 30 }

[item_window]
rect = { x = -999, y = -999, w = 520, h = 286 }
n_row = 10
column_pos = [1, 34, 400]
info_label_rect = { x = 5, y = 260, w = 10, h = 10 }

[item_info_window]
rect = { x = -999, y = -999, w = 450, h = 300 }
item_image = { x = 2, y = 0, w = 48, h = 48 }
item_name = { x = 50, y = 2 }
item_kind = { x = 50, y = 25 }
desc_text = { x = 24, y = 48, w = 422 }
desc_text_icon = { x = 3, y = 52, w = 16, h = 16 }

[equip_window]
rect = { x = -999, y = -999, w = 450, h = 286 }
n_row = 10
column_pos = [1, 28, 58]

[scrolling_text_window]
line_space = 30
speed = 1.5

[info_window]
rect = { x = -999, y = -999, w = 500, h = 300 }

[status_window]
image_rect = { x = 5, y = 5, w = 48, h = 96 }
name_label_rect = { x = 50, y = 3 }
hp_label_rect = { x = 57, y = 32 }
sp_label_rect = { x = 57, y = 50 }
str_label_rect = { x = 5, y = 100 }
vit_label_rect = { x = 5, y = 120 }
dex_label_rect = { x = 5, y = 140 }
int_label_rect = { x = 5, y = 160 }
wil_label_rect = { x = 5, y = 180 }
cha_label_rect = { x = 5, y = 200 }

[game_info_window]
money_label_rect = { x = 5, y = 5 }

[skill_window]
gauge_rect = { x = 80, y = 2, w = 50, h = 18 }
label_rect = { x = 5, y = 2, w = 80, h = 18 }
gauge_w = 140
gauge_h = 24
n_row = 10
n_column = 3

[quest_window]
rect = { x = -999, y = -999, w = 500, h = 300 }
n_row = 6

[label_widget]
h = 24
left_margin = 3

[list_widget]
h_row_default = 26
h_row_with_text = 24
left_margin = 5

[vscroll_widget]
width = 23
button_height = 26
min_knob_size = 20
button_repeat_duration = 350

[time_info]
time_label = { x = 2, y = 16 }
date_label = { x = 2, y = 3 }

[progress_bar]
rect = { x = -999, y = 35, w = 120, h = 15}

[sidebar]
icon_w = 32
icon_h = 32
space = 4
