
[normal]
return = "enter"
d = "drop_item"
e = "eat_item"
f = "shot"
g = "pick_up_item"
i = "open_item_menu"
o = "open_game_info_win"
q = "drink_item"
s = "open_status_win"
t = "targeting_mode"
w = "open_equip_win"
escape = "open_exit_win"

[dialog]
return = "enter"
escape = "cancel"
tab = "rotate_window_right"
a = "item_infomation"

[targeting]
return = "enter"
escape = "cancel"
