[package]
name = "rusted-ruins-makepak"
version = "0.3.0"
edition = "2018"
authors = ["T. Okubo <t.okubo.rx78+devel@gmail.com>"]

[dependencies]
lazy_static = "1"
regex = "1"
serde = "1"
serde_derive = "1"
failure = "0.1.1"
toml = "0.4"
tar = "0.4"
clap = "2"
image = "0.21"
nom = { version = "4.1", features = ["regexp_macros"] }

[dependencies.rusted-ruins-array2d]
path = "../array2d"

[dependencies.rusted-ruins-common]
path = "../common"


